FROM docker.m.daocloud.io/library/nginx:stable-alpine

COPY apps/enduser/dist/ /usr/share/nginx/html/
COPY apps/enduser/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
