"""SQLAlchemy 2.0 ORM models — table mappings for PostgreSQL ontology metadata."""

from ontology.core.models.datasource import (
    CredentialModel,
    DatasetGovernanceModel,
    DataSourceModel,
    SyncTaskModel,
)
from ontology.core.models.ontology import (
    ActionExecutionLogModel,
    ActionTypeModel,
    Base,
    BranchModel,
    InterfacePropertyModel,
    InterfaceTypeModel,
    LinkTypeModel,
    ObjectStateModel,
    ObjectTypeGroupModel,
    ObjectTypeModel,
    ObjectTypeSharedPropertyModel,
    OntologyModel,
    OutboxModel,
    PropertyDefModel,
    SharedPropertyModel,
    StructModel,
    ValueTypeModel,
)
from ontology.core.models.permission import (
    AccessRequestModel,
    AuditLogModel,
    GroupMembershipModel,
    GroupModel,
    MarkingAssignmentModel,
    MarkingCategoryModel,
    MarkingGrantModel,
    MarkingModel,
    OrganizationModel,
    PrincipalModel,
    ProjectModel,
    PropertyMaskingPolicyModel,
    RoleAssignmentModel,
    RoleModel,
    RowSecurityPolicyModel,
    ServiceUserModel,
    SpaceModel,
    SpaceOrganizationModel,
    UserModel,
)
from ontology.core.models.pipeline import (
    PipelineExecutionModel,
    PipelineModel,
    PipelineNodeRunModel,
    PipelineScheduleModel,
    PipelineStateHistoryModel,
    PipelineVersionModel,
)

__all__ = [
    "Base",
    "OntologyModel",
    "ObjectTypeModel",
    "PropertyDefModel",
    "LinkTypeModel",
    "ActionTypeModel",
    "InterfaceTypeModel",
    "InterfacePropertyModel",
    "ValueTypeModel",
    "SharedPropertyModel",
    "ObjectTypeSharedPropertyModel",
    "StructModel",
    "ObjectTypeGroupModel",
    "BranchModel",
    "ActionExecutionLogModel",
    "OutboxModel",
    "ObjectStateModel",
    "DataSourceModel",
    "CredentialModel",
    "SyncTaskModel",
    "DatasetGovernanceModel",
    # ADR-018 Pipeline Builder.
    "PipelineModel",
    "PipelineVersionModel",
    "PipelineExecutionModel",
    "PipelineNodeRunModel",
    "PipelineStateHistoryModel",
    "PipelineScheduleModel",
    # ADR-016 permission governance (Phase 0).
    "OrganizationModel",
    "SpaceModel",
    "SpaceOrganizationModel",
    "ProjectModel",
    "PrincipalModel",
    "UserModel",
    "GroupModel",
    "GroupMembershipModel",
    "ServiceUserModel",
    # ADR-016 permission governance (Phase 1: RBAC).
    "RoleModel",
    "RoleAssignmentModel",
    # ADR-016 permission governance (Phase 2: MAC / Marking).
    "MarkingCategoryModel",
    "MarkingModel",
    "MarkingGrantModel",
    "MarkingAssignmentModel",
    # ADR-016 permission governance (Phase 3: ABAC row/column).
    "RowSecurityPolicyModel",
    "PropertyMaskingPolicyModel",
    # ADR-016 permission governance (Phase 4: audit + JIT).
    "AuditLogModel",
    "AccessRequestModel",
]
