"""SQLAlchemy 2.0 ORM models for Pipeline Builder.

Design follows ADR-018 D8 (Airflow 3 independent version table, Prefect
state history, JSONB whole-graph storage).  All models use the standard
Gaia ORM conventions:
- UUID v4 hex primary keys
- VARCHAR for enums (validated at pydantic layer)
- JSONB for flexible/config fields
- utcnow() for all timestamps
- FK indexes on all foreign key columns (Airflow PR #39638 lesson)
"""

from datetime import datetime
from typing import Any

from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, Integer, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from ontology.core.models.defaults import JSONBType, new_uuid, utcnow
from ontology.core.models.ontology import Base

# ═══════════════════════════════════════════════════════════════════
# Pipelines
# ═══════════════════════════════════════════════════════════════════


class PipelineModel(Base):
    """Pipeline definition — current-version metadata.

    Only stores metadata and the current_version_id pointer. The actual
    IR content lives in pipeline_versions.graph (JSONB).  This keeps the
    pipeline_versions table append-only so every change is a reversible
    version boundary.
    """

    __tablename__ = "pipelines"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_uuid)
    api_name: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)
    display_name: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, default="")
    # DRAFT | PUBLISHED | DEPRECATED | ARCHIVED
    status: Mapped[str] = mapped_column(String(20), default="DRAFT")
    # Point-increment only — versioning is handled via pipeline_versions table.
    # NULL = no version has been saved yet (initial creation).
    # use_alter=True: breaks the circular FK (pipelines.current_version_id ↔ pipeline_versions.pipeline_id)
    # so SQLAlchemy emits ALTER TABLE after both tables exist (avoids CREATE ordering issues).
    current_version_id: Mapped[str | None] = mapped_column(
        String(32),
        ForeignKey("pipeline_versions.id", ondelete="RESTRICT", use_alter=True, name="fk_pipelines_current_version_id"),
        nullable=True,
        index=True,
    )
    # Write mode for builds: FULL_REFRESH | APPEND
    write_mode: Mapped[str] = mapped_column(String(20), default="FULL_REFRESH")
    # Target output Dataset (must be MANAGED Iceberg — VIRTUAL forbidden, red line #9)
    sink_dataset_api_name: Mapped[str] = mapped_column(String(255), nullable=False)
    # Phase 2: Ontology mapping config (JSONB, nullable)
    ontology_mapping_config: Mapped[dict[str, Any] | None] = mapped_column(JSONBType, nullable=True)
    # ADR-016: pipeline ownership
    owner_id: Mapped[str | None] = mapped_column(String(32), nullable=True)
    project_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("projects.id", ondelete="SET NULL"), nullable=True, index=True
    )
    # Soft-delete: preserve execution audit (physical delete only via admin, guarded by RESTRICT FKs)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)

    __table_args__ = {"comment": "管道定义 — 当前生效版本的元信息"}


# ═══════════════════════════════════════════════════════════════════
# Pipeline Versions
# ═══════════════════════════════════════════════════════════════════


class PipelineVersionModel(Base):
    """Pipeline version — one row per edit, append-only.

    ``graph`` JSONB holds the complete IR (nodes + edges + per-node config).
    ``inferred_schema`` caches the SchemaInferenceEngine output for this
    version so execution always uses the stored snapshot (reproducible builds).
    """

    __tablename__ = "pipeline_versions"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_uuid)
    pipeline_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("pipelines.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Auto-increment per pipeline (1, 2, 3…). Generated by service layer as MAX+1.
    version_number: Mapped[int] = mapped_column(Integer, nullable=False)
    # Complete Pipeline IR: { nodes: [...], edges: [...], metadata: {...} }
    graph: Mapped[dict[str, Any]] = mapped_column(JSONBType, nullable=False, default=dict)
    # SchemaInferenceEngine output snapshot (cached for reproducibility)
    inferred_schema: Mapped[dict[str, Any] | None] = mapped_column(JSONBType, nullable=True)
    # User-supplied or auto-generated change description
    change_summary: Mapped[str] = mapped_column(Text, default="")
    created_by: Mapped[str | None] = mapped_column(String(32), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)

    __table_args__ = (
        UniqueConstraint("pipeline_id", "version_number", name="uq_pipeline_versions_number"),
        {"comment": "管道版本历史 — 每次编辑一行，graph JSONB 整存 IR"},
    )


# ═══════════════════════════════════════════════════════════════════
# Pipeline Executions (Builds)
# ═══════════════════════════════════════════════════════════════════


class PipelineExecutionModel(Base):
    """Pipeline execution (build) record.

    One row per trigger (manual / cron / event).  Current state is
    denormalised on this table so the list query doesn't need to JOIN
    state_history (Prefect PR #7138 lesson).  Full state transition
    chain lives in pipeline_state_history.
    """

    __tablename__ = "pipeline_executions"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_uuid)
    pipeline_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("pipelines.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    # The pipeline_version used for this execution (RESTRICT — prevent deletion of referenced versions)
    version_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("pipeline_versions.id", ondelete="RESTRICT"), nullable=False, index=True
    )
    # MANUAL | SCHEDULE | UPSTREAM_EVENT
    trigger_type: Mapped[str] = mapped_column(String(20), nullable=False)
    triggered_by: Mapped[str | None] = mapped_column(String(32), nullable=True)
    # Denormalised current state (canonical chain in state_history): PENDING | RUNNING | SUCCESS | FAILED | CANCELLED
    current_state: Mapped[str] = mapped_column(String(20), default="PENDING", index=True)
    # Denormalised timing fields (sorted queries don't JOIN history)
    state_started_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    # Kestra mapping (decoupling, 1:1 relationship — no separate mapping table)
    kestra_execution_id: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    kestra_flow_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    kestra_namespace: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # Denormalised error message (for list display without history JOIN)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Output Iceberg snapshot ID (data rollback anchor — switch current_snapshot_id)
    output_snapshot_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # Extended metadata (rows_total / bytes_total / cost_estimate, etc.)
    execution_meta: Mapped[dict[str, Any]] = mapped_column(JSONBType, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, index=True)

    __table_args__ = {"comment": "构建执行记录 — 一次触发一行，冗余当前状态加速列表查询"}


# ═══════════════════════════════════════════════════════════════════
# Pipeline Node Runs
# ═══════════════════════════════════════════════════════════════════


class PipelineNodeRunModel(Base):
    """Per-node execution status within a build.

    Enables diagnostics: which node failed, how long did each step take,
    how many rows passed through each transform.
    """

    __tablename__ = "pipeline_node_runs"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_uuid)
    execution_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("pipeline_executions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # IR node ID (matches graph.nodes[].id)
    node_id: Mapped[str] = mapped_column(String(255), nullable=False)
    # Source | Transform | GenericKestraTask | QualityCheck | Sink
    node_type: Mapped[str] = mapped_column(String(50), nullable=False)
    # Execution engine: duckdb | seatunnel | trino | kestra_plugin
    engine: Mapped[str | None] = mapped_column(String(20), nullable=True)
    current_state: Mapped[str] = mapped_column(String(20), default="PENDING", index=True)
    started_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    duration_ms: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True)
    attempt: Mapped[int] = mapped_column(Integer, default=1)
    kestra_taskrun_id: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    # Observability fields (nullable — collection logic filled in Phase 2)
    rows_in: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    rows_out: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    bytes_processed: Mapped[int | None] = mapped_column(BigInteger, nullable=True)
    node_run_meta: Mapped[dict[str, Any]] = mapped_column(JSONBType, nullable=False, default=dict)

    __table_args__ = {"comment": "节点级执行状态 — 每个构建内节点一行"}


# ═══════════════════════════════════════════════════════════════════
# Pipeline State History
# ═══════════════════════════════════════════════════════════════════


class PipelineStateHistoryModel(Base):
    """Execution state transition audit trail.

    Each state change inserts one row.  Used for failure diagnosis
    and audit: "when did it fail, how long was it running, who cancelled it".
    """

    __tablename__ = "pipeline_state_history"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_uuid)
    execution_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("pipeline_executions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    from_state: Mapped[str | None] = mapped_column(String(20), nullable=True)
    to_state: Mapped[str] = mapped_column(String(20), nullable=False)
    reason: Mapped[str | None] = mapped_column(String(255), nullable=True)
    changed_by: Mapped[str | None] = mapped_column(String(32), nullable=True)
    changed_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, index=True)

    __table_args__ = {"comment": "执行状态变更历史 — 每次状态变更一行"}


# ═══════════════════════════════════════════════════════════════════
# Pipeline Schedules
# ═══════════════════════════════════════════════════════════════════


class PipelineScheduleModel(Base):
    """Schedule (trigger config) for a pipeline — independent resource.

    Aligned with Palantir /v2/orchestration/schedules. A pipeline can
    have multiple schedules (e.g. weekday incremental + monthly full),
    independently enabled/disabled.
    """

    __tablename__ = "pipeline_schedules"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_uuid)
    pipeline_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("pipelines.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # Schedule api_name — unique within its pipeline
    api_name: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    display_name: Mapped[str] = mapped_column(String(255), default="")
    # Trigger config JSONB (MVP single trigger; structure reserves AND/OR nesting)
    #   {"type": "time", "cron": "0 9 * * 1-5", "tz": "Asia/Shanghai"}
    #   {"type": "webhook", "key": "orders-arrived"}
    trigger: Mapped[dict[str, Any]] = mapped_column(JSONBType, nullable=False, default=dict)
    # Build action config: { force_build, retry_count, timeout_minutes, abort_on_failure }
    action_config: Mapped[dict[str, Any]] = mapped_column(JSONBType, nullable=False, default=dict)
    enabled: Mapped[bool] = mapped_column(Boolean, default=True)
    # Kestra trigger ID for decoupling (filled on deploy)
    kestra_trigger_id: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_by: Mapped[str | None] = mapped_column(String(32), nullable=True)
    project_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("projects.id", ondelete="SET NULL"), nullable=True, index=True
    )
    created_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=utcnow, onupdate=utcnow)

    __table_args__ = (
        UniqueConstraint("pipeline_id", "api_name", name="uq_pipeline_schedules_api_name"),
        {"comment": "管道调度 — 独立资源，一个管道可有多个调度"},
    )
