"""Impact summary builders for HITL approval previews.

Per the HITL best practice "show the effect of the action, not the JSON"
(https://ai-tldr.dev/learn/building-ai-apps/ai-ux-patterns/human-in-the-loop-ux/),
the AG-UI interrupt's ``message`` field (auto-generated by pydantic-ai's
``approval_to_interrupt`` as ``Approve <tool>(<raw_args_json>)?``) shows the
LLM's raw arguments — which may contain unresolved defaults like
``ontology=""`` (filled by ``ctx.deps.ontology`` at execution time).

This module builds a human-readable ``impact_summary`` + the
``resolved_args`` (defaults applied) that
``MetadataApprovalToolset`` attaches to ``ApprovalRequired.metadata``. The
frontend ``BatchApprovalPanel`` reads ``metadata.impact_summary`` to render
a plain-language preview ("将创建对象类型 优惠券 (Coupon)...") instead of
the raw JSON, so the user can predict the real outcome from the preview
alone — the core requirement of "propose → review → commit".

Design:
- Each builder is a pure function ``(args, ctx) -> ImpactPreview``. No I/O,
  no service calls — it only reformats the already-validated args + reads
  ``ctx.deps`` for default resolution. This keeps the approval gate fast
  (no DB round-trip) and side-effect-free (the real execution happens only
  after approval).
- Builders are registered by tool name in ``_BUILDERS``. Adding a new
  write/action tool = adding one entry here. Tools without a registered
  builder fall back to the raw-args message (current behaviour).
- ``resolved_args`` carries the args AFTER default resolution (e.g.
  ``ontology="Marketing"`` instead of ``""``), so the frontend can show
  the user what will ACTUALLY execute, not what the LLM typed.

The impact text mirrors the ``impact`` strings already built inside the
``*_logic`` functions (e.g. ``define_object_type_logic``), but lifted here
as a pure preview (the ``*_logic`` version is still used for audit logging
inside ``executor.execute_write`` — they are intentionally duplicated
rather than coupled, because the logic function runs AFTER approval while
the builder runs BEFORE).
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, TypedDict

from pydantic_ai._run_context import AgentDepsT, RunContext

__all__ = ["ImpactPreview", "ImpactBuilder", "build_impact", "register_impact_builder"]


class ImpactPreview(TypedDict):
    """The preview payload attached to ``ApprovalRequired.metadata``.

    - ``impact_summary``: plain-language description of what will happen
      ("将创建对象类型 优惠券 (Coupon),主键 couponNo,含 4 个属性...").
      The frontend renders this instead of the raw JSON args.
    - ``resolved_args``: the args AFTER default resolution (e.g.
      ``ontology="Marketing"`` instead of ``""``). Lets the frontend show
      the real execution inputs, not the LLM's raw (possibly empty) values.
    """

    impact_summary: str
    resolved_args: dict[str, Any]


class ImpactBuilder(Protocol[AgentDepsT]):
    """Build an impact preview from validated tool args + run context.

    Pure function: no I/O, no service calls. Only reformats args + reads
    ``ctx.deps`` for default resolution.
    """

    def __call__(self, args: dict[str, Any], ctx: RunContext[AgentDepsT]) -> ImpactPreview: ...


# Tool-name → builder registry. Tools without an entry fall back to the
# raw-args message (no impact_summary).
_BUILDERS: dict[str, ImpactBuilder[Any]] = {}


def register_impact_builder(tool_name: str) -> Callable[[ImpactBuilder[Any]], ImpactBuilder[Any]]:
    """Decorator: register an impact builder for a tool name.

    Usage::

        @register_impact_builder("define_object_type")
        def _build(args, ctx) -> ImpactPreview: ...
    """

    def _decorator(func: ImpactBuilder[Any]) -> ImpactBuilder[Any]:
        _BUILDERS[tool_name] = func
        return func

    return _decorator


def build_impact(tool_name: str, args: dict[str, Any], ctx: RunContext[AgentDepsT]) -> ImpactPreview | None:
    """Build the impact preview for a tool call, or None if no builder.

    Called by ``MetadataApprovalToolset`` before raising ``ApprovalRequired``.
    """
    builder = _BUILDERS.get(tool_name)
    if builder is None:
        return None
    return builder(args, ctx)


# ── Default-resolution helper ────────────────────────────────────────────
# write/action tools default ``ontology`` from ``ctx.deps.ontology`` (see
# the ``ontology = ontology or ctx.deps.ontology`` line in each tool body).
# The preview must reflect this resolution so the user sees the real target.


def _resolve_ontology(args: dict[str, Any], ctx: RunContext[Any]) -> str:
    """Return the ontology that will actually be used at execution time."""
    raw = str(args.get("ontology") or "")
    if raw:
        return raw
    # Mirror the tool-body fallback. AppState.ontology is set from
    # forwardedProps.ontology in /ai/agent.
    deps_ontology = getattr(ctx.deps, "ontology", "")
    return str(deps_ontology) or "(未指定)"


# ── Builders for the write/action tools ──────────────────────────────────


@register_impact_builder("define_object_type")
def _define_object_type(args: dict[str, Any], ctx: RunContext[Any]) -> ImpactPreview:
    """Preview for define_object_type — mirrors define_object_type_logic.impact."""
    ontology = _resolve_ontology(args, ctx)
    display_name = str(args.get("display_name") or "")
    api_name = str(args.get("api_name") or "")
    storage_type = str(args.get("storage_type") or "MANAGED")
    primary_key = str(args.get("primary_key") or "")
    properties = args.get("properties") or []
    prop_count = len(properties) if isinstance(properties, list) else 0

    pk_desc = primary_key or "(由属性标记推导)"
    managed_note = "。MANAGED 类型会触发 Doris 建表 + 索引同步" if storage_type == "MANAGED" else ""
    summary = (
        f"将在本体 {ontology} 创建对象类型 {display_name} ({api_name}),"
        f"主键 {pk_desc},storage_type={storage_type},含 {prop_count} 个属性{managed_note}。"
    )
    resolved = {**args, "ontology": ontology}
    return {"impact_summary": summary, "resolved_args": resolved}


@register_impact_builder("add_property")
def _add_property(args: dict[str, Any], ctx: RunContext[Any]) -> ImpactPreview:
    """Preview for add_property — mirrors add_property_logic.impact."""
    ontology = _resolve_ontology(args, ctx)
    object_type = str(args.get("object_type") or "")
    display_name = str(args.get("display_name") or "")
    data_type = str(args.get("data_type") or "")
    indexed = bool(args.get("indexed", False))

    index_note = "。会触发 Doris 索引表 schema 演进" if indexed else ""
    summary = (
        f"将在本体 {ontology} 的对象类型 {object_type} 添加属性 {display_name},"
        f"类型 {data_type},indexed={indexed}{index_note}。"
    )
    resolved = {**args, "ontology": ontology}
    return {"impact_summary": summary, "resolved_args": resolved}


@register_impact_builder("define_link_type")
def _define_link_type(args: dict[str, Any], ctx: RunContext[Any]) -> ImpactPreview:
    """Preview for define_link_type — mirrors define_link_type_logic.impact."""
    ontology = _resolve_ontology(args, ctx)
    display_name = str(args.get("display_name") or "")
    source = str(args.get("source_object_type") or "")
    target = str(args.get("target_object_type") or "")
    cardinality = str(args.get("cardinality") or "MANY")
    direction = str(args.get("direction") or "OUTGOING")

    summary = (
        f"将在本体 {ontology} 创建关系 {display_name}: "
        f"{source} -> {target}, cardinality={cardinality}, direction={direction}。"
    )
    resolved = {**args, "ontology": ontology}
    return {"impact_summary": summary, "resolved_args": resolved}


@register_impact_builder("link_dataset")
def _link_dataset(args: dict[str, Any], ctx: RunContext[Any]) -> ImpactPreview:
    """Preview for link_dataset — mirrors link_dataset_logic.impact."""
    ontology = _resolve_ontology(args, ctx)
    object_type = str(args.get("object_type") or "")
    dataset_api_name = str(args.get("dataset_api_name") or "")
    mappings = args.get("column_mappings") or []
    mapping_count = len(mappings) if isinstance(mappings, list) else 0

    summary = (
        f"将在本体 {ontology} 绑定对象类型 {object_type} -> 数据集 {dataset_api_name},"
        f"映射 {mapping_count} 个属性到物理列。"
    )
    resolved = {**args, "ontology": ontology}
    return {"impact_summary": summary, "resolved_args": resolved}


@register_impact_builder("invoke_action")
def _invoke_action(args: dict[str, Any], ctx: RunContext[Any]) -> ImpactPreview:
    """Preview for invoke_action — mirrors invoke_action_logic.impact.

    Note: the real risk_level is resolved from the ActionType definition at
    execution time (inside invoke_action_logic). The preview can only show
    the LLM-supplied action_type + object_type + parameters; the frontend
    already treats invoke_action as risk='unknown' (per-item review) until
    the ActionType is resolved."""
    ontology = _resolve_ontology(args, ctx)
    object_type = str(args.get("object_type") or "")
    action_type = str(args.get("action_type") or "")
    parameters = args.get("parameters") or {}

    summary = (
        f"将在本体 {ontology} 执行动作 {action_type} 于对象类型 {object_type},"
        f"参数: {parameters or {}}。"
        f"动作风险等级将在执行时从 ActionType 定义解析。"
    )
    resolved = {**args, "ontology": ontology}
    return {"impact_summary": summary, "resolved_args": resolved}


@register_impact_builder("validate_action")
def _validate_action(args: dict[str, Any], ctx: RunContext[Any]) -> ImpactPreview:
    """Preview for validate_action (pure check, no side effects)."""
    ontology = _resolve_ontology(args, ctx)
    object_type = str(args.get("object_type") or "")
    action_type = str(args.get("action_type") or "")

    summary = f"将在本体 {ontology} 预校验动作 {action_type} 于对象类型 {object_type}（仅校验,不执行）。"
    resolved = {**args, "ontology": ontology}
    return {"impact_summary": summary, "resolved_args": resolved}
