"""Metadata-layer tools (4) — Agent's "get oriented" tools.

Per docs/architecture/ontology-tool-layer.md §5.1, these are the prerequisite
tools an Agent calls before any instance-layer operation: they answer "which
ontologies exist", "which object types are in an ontology", "what's the schema
of an object type", "what's the schema of a link type".

All four are thin wrappers over ``OntologyService`` methods. They carry no
business logic. The tool contract (name / description / parameter schema) is
auto-generated by pydantic-ai from the function signature + type annotations
+ docstring — see the Tool Contract Quality spec in the design doc.

Architecture (docs/architecture/rfcs/AI-context-scoping.md):
  - ``<tool>_logic(executor, ...)`` is the protocol-agnostic single source of
    truth. MCP exposure (``protocols/mcp_server.py``) calls it directly.
  - ``build_metadata_toolset`` produces the AG-UI exposure: ``@ts.tool``
    wrappers reading ``ctx.deps.ontology`` (the ontology open in the Web UI)
    to default the ``ontology`` arg, keeping the assistant inside the current
    ontology.
  - ``list_ontologies`` is intentionally NOT registered on the AG-UI path —
    the Web UI always has a concrete ontology open, so enumerating others has
    no business need and would be an over-reaching entry point. MCP (external
    Agents with no "current ontology") registers it separately.
"""

from __future__ import annotations

from typing import Any

from pydantic_ai import RunContext
from pydantic_ai.toolsets import FunctionToolset

from ontology.tools.executor import ToolExecutor
from ontology.tools.state import AppState
from ontology.tools.toolsets._contracts import (
    DESCRIBE_LINK_TYPE_DESC,
    DESCRIBE_OBJECT_TYPE_DESC,
    LIST_OBJECT_TYPES_DESC,
)

# ── Shared logic (single source of truth, protocol-agnostic) ─────────────


async def list_ontologies_logic(executor: ToolExecutor) -> list[dict[str, Any]]:
    """List all ontologies. Protocol-agnostic — used by the MCP path only.

    The AG-UI path does not expose list_ontologies (the Web UI always has a
    concrete ontology open). See module docstring + AI-context-scoping RFC.
    """
    svc = executor.container.ontology_service
    ontologies = await executor.audit_call("list_ontologies", {}, svc.list_ontologies())
    if isinstance(ontologies, dict) and "error" in ontologies:
        return [ontologies]  # propagate error envelope
    return [
        {
            "api_name": o.api_name,
            "display_name": o.display_name,
            "description": o.description,
        }
        for o in ontologies
    ]


async def list_object_types_logic(executor: ToolExecutor, ontology: str) -> list[dict[str, Any]]:
    """List all object types in an ontology. Protocol-agnostic."""
    svc = executor.container.ontology_service
    ots = await executor.audit_call(
        "list_object_types",
        {"ontology": ontology},
        svc.list_object_types(ontology),
    )
    if isinstance(ots, dict) and "error" in ots:
        return [ots]
    return [
        {
            "api_name": ot.api_name,
            "display_name": ot.display_name,
            "description": ot.description,
            "storage_type": ot.storage_type,
        }
        for ot in ots
    ]


async def describe_object_type_logic(executor: ToolExecutor, ontology: str, object_type: str) -> dict[str, Any]:
    """Get the full schema of an object type. Protocol-agnostic."""
    svc = executor.container.ontology_service
    ot = await executor.audit_call(
        "describe_object_type",
        {"ontology": ontology, "object_type": object_type},
        svc.get_object_type(ontology, object_type),
    )
    if isinstance(ot, dict) and "error" in ot:
        return ot
    return {
        "api_name": ot.api_name,
        "display_name": ot.display_name,
        "description": ot.description,
        "primary_key": ot.primary_key,
        "storage_type": ot.storage_type,
        "properties": [
            {
                "api_name": p.api_name,
                "display_name": p.display_name,
                "data_type": str(p.data_type),
                "is_primary_key": p.is_primary_key,
                "nullable": p.nullable,
                # filterable follows the indexed flag — only indexed
                # columns are efficiently filterable in Doris. Non-indexed
                # columns can still be filtered but may trigger full scans.
                "filterable": p.indexed or p.is_primary_key,
                # sortable is true for primitive/scalar types that have a
                # meaningful total order; complex types (array/struct/
                # vector/geo/media) cannot be sorted.
                "sortable": str(p.data_type)
                not in {
                    "ARRAY",
                    "STRUCT",
                    "VECTOR",
                    "GEOPOINT",
                    "GEOSHAPE",
                    "MEDIA_REFERENCE",
                    "ATTACHMENT",
                },
            }
            for p in ot.properties
        ],
    }


async def describe_link_type_logic(executor: ToolExecutor, ontology: str, link_type: str) -> dict[str, Any]:
    """Get the schema of a link type. Protocol-agnostic."""
    svc = executor.container.ontology_service
    links = await executor.audit_call(
        "describe_link_type",
        {"ontology": ontology, "link_type": link_type},
        svc.list_link_types(ontology),
    )
    if isinstance(links, dict) and "error" in links:
        return links
    # list_link_types returns all link types; filter to the requested one.
    match = next(
        (lt for lt in links if lt.api_name == link_type),
        None,
    )
    if match is None:
        return {
            "error": {
                "code": "OBJECT_NOT_FOUND",
                "message": f"link_type {link_type!r} not found in ontology {ontology!r}",
            }
        }
    return {
        "api_name": match.api_name,
        "display_name": match.display_name,
        "description": match.description,
        "source_object_type_id": match.source_object_type_id,
        "target_object_type_id": match.target_object_type_id,
        "cardinality": match.cardinality,
        "direction": match.direction,
        "directional": True,
        "has_properties": False,  # Sprint 2+: read from link schema
    }


async def describe_ontology_logic(executor: ToolExecutor, ontology: str) -> dict[str, Any]:
    """Get the full metadata of an ontology in one call. Protocol-agnostic.

    Thin wrapper over ``OntologyService.assemble_ontology_metadata`` (ADR-020).
    Exposed on MCP + REST only — the AG-UI path does NOT register it (the
    built-in Agent already receives the ontology structure via
    ``build_ontology_summary`` text injection; exposing this would only
    induce redundant full-payload calls). See ADR-020 §2.
    """
    svc = executor.container.ontology_service
    meta = await executor.audit_call(
        "describe_ontology",
        {"ontology": ontology},
        svc.assemble_ontology_metadata(ontology),
    )
    if isinstance(meta, dict) and "error" in meta:
        return meta
    # audit_call returns Any; success path is OntologyFullMetadata.
    return dict(meta.model_dump(mode="json"))


# ── AG-UI exposure (pydantic-ai toolset, reads ctx.deps.ontology) ────────


def build_metadata_toolset(executor: ToolExecutor) -> FunctionToolset[AppState]:
    """Build the metadata-layer toolset for the AG-UI path.

    Each ``@ts.tool`` wrapper reads ``ctx.deps.ontology`` (the ontology the
    user has open in the Web UI) and defaults the ``ontology`` arg to it when
    the LLM omits it — so the assistant stays inside the current ontology.

    ``list_ontologies`` is deliberately NOT registered here: the Web UI always
    operates inside a concrete ontology, so enumerating all ontologies has no
    business need. MCP registers it separately via ``list_ontologies_logic``.
    See docs/architecture/rfcs/AI-context-scoping.md §9.
    """
    ts: FunctionToolset[AppState] = FunctionToolset()

    @ts.tool(description=LIST_OBJECT_TYPES_DESC)
    async def list_object_types(ctx: RunContext[AppState], ontology: str = "") -> list[dict[str, Any]]:
        """List all object types in an ontology. (See shared description.)"""
        ontology = ontology or ctx.deps.ontology
        return await list_object_types_logic(executor, ontology)

    @ts.tool(description=DESCRIBE_OBJECT_TYPE_DESC)
    async def describe_object_type(
        ctx: RunContext[AppState], ontology: str = "", object_type: str = ""
    ) -> dict[str, Any]:
        """Get the full schema of an object type. (See shared description.)"""
        ontology = ontology or ctx.deps.ontology
        return await describe_object_type_logic(executor, ontology, object_type)

    @ts.tool(description=DESCRIBE_LINK_TYPE_DESC)
    async def describe_link_type(ctx: RunContext[AppState], ontology: str = "", link_type: str = "") -> dict[str, Any]:
        """Get the schema of a link type. (See shared description.)"""
        ontology = ontology or ctx.deps.ontology
        return await describe_link_type_logic(executor, ontology, link_type)

    return ts
