"""initial_schema

Revision ID: caaee34d415d
Revises: 
Create Date: 2026-05-19 02:05:57.413322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caaee34d415d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hub_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('agent', 'mcp', 'skill', 'tool', name='hubitemtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('scenario', sa.String(length=100), nullable=True),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.Enum('preset', 'manual', 'upload', name='sourcetype'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'published', 'rejected', 'disabled', 'archived', name='hubitemstatus'), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'blocking', name='risklevel'), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('discoverable', sa.Boolean(), nullable=False),
    sa.Column('allow_existing_references', sa.Boolean(), nullable=False),
    sa.Column('force_disabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hub_item_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_item_id', sa.Uuid(), nullable=False),
    sa.Column('target_item_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.Enum('uses', 'invokes', 'depends_on', 'provides', name='relationtype'), nullable=False),
    sa.Column('relation_scope', sa.Enum('management', 'runtime', name='relationscope'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_item_id'], ['hub_items.id'], ),
    sa.ForeignKeyConstraint(['target_item_id'], ['hub_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_item_id', 'target_item_id', 'relation_type', 'relation_scope', name='uq_relation_source_target_type_scope')
    )
    op.create_index('ix_relation_source_item_id', 'hub_item_relations', ['source_item_id'], unique=False)
    op.create_index('ix_relation_source_scope', 'hub_item_relations', ['source_item_id', 'relation_scope'], unique=False)
    op.create_index('ix_relation_target_item_id', 'hub_item_relations', ['target_item_id'], unique=False)
    op.create_index('ix_relation_target_scope', 'hub_item_relations', ['target_item_id', 'relation_scope'], unique=False)
    op.create_table('hub_item_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hub_item_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hub_item_id'], ['hub_items.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hub_item_tags_item_tag', 'hub_item_tags', ['hub_item_id', 'tag_id'], unique=True)
    op.create_table('hub_item_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hub_item_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manifest_json', sa.JSON(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('input_schema', sa.JSON(), nullable=True),
    sa.Column('output_schema', sa.JSON(), nullable=True),
    sa.Column('permission_json', sa.JSON(), nullable=True),
    sa.Column('runtime_compatibility', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', 'rejected', 'change_required', 'published', 'deprecated', 'archived', name='hubitemversionstatus'), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'blocking', name='risklevel'), nullable=False),
    sa.Column('package_hash', sa.String(length=256), nullable=True),
    sa.Column('change_log', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hub_item_id'], ['hub_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hub_item_versions_item_version', 'hub_item_versions', ['hub_item_id', 'version'], unique=True)
    op.create_table('approval_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hub_item_id', sa.Uuid(), nullable=False),
    sa.Column('hub_item_version_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('submit', 'approve', 'reject', 'request_change', name='approvalaction'), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hub_item_id'], ['hub_items.id'], ),
    sa.ForeignKeyConstraint(['hub_item_version_id'], ['hub_item_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lifecycle_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hub_item_id', sa.Uuid(), nullable=False),
    sa.Column('hub_item_version_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('created', 'submitted', 'approved', 'rejected', 'change_requested', 'published', 'deprecated', 'rolled_back', 'disabled', 'archived', 'scanned', name='eventtype'), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('operator', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hub_item_id'], ['hub_items.id'], ),
    sa.ForeignKeyConstraint(['hub_item_version_id'], ['hub_item_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hub_item_id', sa.Uuid(), nullable=False),
    sa.Column('hub_item_version_id', sa.Uuid(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', 'blocking', name='risklevel'), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('scanner_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hub_item_id'], ['hub_items.id'], ),
    sa.ForeignKeyConstraint(['hub_item_version_id'], ['hub_item_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_report_id', sa.Uuid(), nullable=False),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='findingseverity'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scan_report_id'], ['scan_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_findings')
    op.drop_table('scan_reports')
    op.drop_table('lifecycle_events')
    op.drop_table('approval_records')
    op.drop_index('ix_hub_item_versions_item_version', table_name='hub_item_versions')
    op.drop_table('hub_item_versions')
    op.drop_index('ix_hub_item_tags_item_tag', table_name='hub_item_tags')
    op.drop_table('hub_item_tags')
    op.drop_index('ix_relation_target_scope', table_name='hub_item_relations')
    op.drop_index('ix_relation_target_item_id', table_name='hub_item_relations')
    op.drop_index('ix_relation_source_scope', table_name='hub_item_relations')
    op.drop_index('ix_relation_source_item_id', table_name='hub_item_relations')
    op.drop_table('hub_item_relations')
    op.drop_table('hub_items')
    op.drop_table('tags')
    op.drop_table('categories')
    # ### end Alembic commands ###
