"""pydantic v2 schemas — API validation and serialization."""

from ontology.core.schemas.action import (
    ActionContext,
    ActionEffectConfig,
    ActionExecutionRequest,
    ActionExecutionResult,
    ActionPreviewResult,
    ActionRule,
    ActionTypeCreate,
    ActionTypeParameter,
    ActionTypeVersion,
    Mutation,
    SubmissionCriterion,
)
from ontology.core.schemas.dataset import (
    ColumnDef,
    Dataset,
    DatasetSchema,
    DatasetSnapshot,
    PartitionField,
    WriteResult,
)
from ontology.core.schemas.datasource import (
    ColumnInfo,
    ConnectionTestResult,
    Credential,
    CredentialCreate,
    CredentialResponse,
    DatasetGovernance,
    DatasetGovernanceCreate,
    DataSource,
    DataSourceCreate,
    DataSourceUpdate,
    ExploreRequest,
    ExploreResult,
    ImpactAnalysis,
    ImpactAnalysisRequest,
    ImpactItem,
    SyncTask,
    SyncTaskCreate,
    SyncTaskUpdate,
    TableInfo,
)
from ontology.core.schemas.index import (
    IndexField,
    IndexTable,
)
from ontology.core.schemas.ontology import (
    ActionType,
    BackingColumnRef,
    Branch,
    DataType,
    InterfaceProperty,
    InterfaceType,
    LinkTypeDef,
    LinkTypeDefCreate,
    ObjectType,
    ObjectTypeCreate,
    ObjectTypeGroup,
    Ontology,
    OntologyCreate,
    OntologyUpdate,
    PropertyDef,
    PropertyDefCreate,
    SharedProperty,
    SharedPropertyCreate,
    Struct,
    StructField,
    ValueType,
)
from ontology.core.schemas.pipeline import (
    PipelineDef,
    PipelineSink,
    PipelineSource,
    PipelineStatus,
    PipelineTransform,
)
from ontology.core.schemas.pipeline_builder import (
    ActionConfig,
    BuildDetailResponse,
    BuildRequest,
    BuildResponse,
    ContractViolation,
    DeployRequest,
    DeployResponse,
    FilterCondition,
    InputContract,
    IREdge,
    IRNode,
    JoinCondition,
    KestraPluginResponse,
    NodeConfig,
    NodePort,
    NodeRunResponse,
    OperatorCatalogResponse,
    OperatorSpecResponse,
    PipelineCreate,
    PipelineErrorResponse,
    PipelineIR,
    PipelineListResponse,
    PipelineResponse,
    PipelineUpdate,
    PipelineVersionResponse,
    QualityRule,
    ScheduleCreate,
    ScheduleResponse,
    ScheduleUpdate,
    Schema,
    SchemaField,
    SortKey,
    StateHistoryResponse,
    TriggerConfig,
    ValidationResponse,
)
from ontology.core.schemas.query import (
    AggregationMetric,
    AggregationRequest,
    ObjectSet,
    QueryFilter,
)

__all__ = [
    # Ontology
    "Ontology",
    "OntologyCreate",
    "OntologyUpdate",
    "ObjectType",
    "ObjectTypeCreate",
    "PropertyDef",
    "PropertyDefCreate",
    "LinkTypeDef",
    "LinkTypeDefCreate",
    "ActionType",
    "InterfaceType",
    "InterfaceProperty",
    "SharedProperty",
    "SharedPropertyCreate",
    "ValueType",
    "Struct",
    "StructField",
    "ObjectTypeGroup",
    "Branch",
    "BackingColumnRef",
    "DataType",
    # Dataset (Iceberg)
    "Dataset",
    "DatasetSchema",
    "ColumnDef",
    "PartitionField",
    "DatasetSnapshot",
    "WriteResult",
    # Dataset (Governance / PG)
    "DatasetGovernance",
    "DatasetGovernanceCreate",
    # DataSource
    "DataSource",
    "DataSourceCreate",
    "DataSourceUpdate",
    "Credential",
    "CredentialCreate",
    "CredentialResponse",
    "ConnectionTestResult",
    # SyncTask
    "SyncTask",
    "SyncTaskCreate",
    "SyncTaskUpdate",
    # Impact Analysis
    "ImpactAnalysis",
    "ImpactAnalysisRequest",
    "ImpactItem",
    # Exploration
    "ExploreRequest",
    "ExploreResult",
    "TableInfo",
    "ColumnInfo",
    # Index
    "IndexTable",
    "IndexField",
    # Query
    "ObjectSet",
    "QueryFilter",
    "AggregationMetric",
    "AggregationRequest",
    # Pipeline (SeaTunnel)
    "PipelineDef",
    "PipelineSource",
    "PipelineTransform",
    "PipelineSink",
    "PipelineStatus",
    # Pipeline Builder
    "PipelineCreate",
    "PipelineUpdate",
    "PipelineResponse",
    "PipelineListResponse",
    "PipelineVersionResponse",
    "PipelineIR",
    "IRNode",
    "IREdge",
    "NodeConfig",
    "NodePort",
    "InputContract",
    "Schema",
    "SchemaField",
    "QualityRule",
    "JoinCondition",
    "SortKey",
    "FilterCondition",
    "DeployRequest",
    "DeployResponse",
    "BuildRequest",
    "BuildResponse",
    "BuildDetailResponse",
    "NodeRunResponse",
    "StateHistoryResponse",
    "ContractViolation",
    "ValidationResponse",
    "TriggerConfig",
    "ActionConfig",
    "ScheduleCreate",
    "ScheduleUpdate",
    "ScheduleResponse",
    "OperatorSpecResponse",
    "KestraPluginResponse",
    "OperatorCatalogResponse",
    "PipelineErrorResponse",
    # Action
    "ActionContext",
    "ActionTypeParameter",
    "ActionRule",
    "ActionEffectConfig",
    "SubmissionCriterion",
    "ActionTypeCreate",
    "ActionExecutionRequest",
    "Mutation",
    "ActionExecutionResult",
    "ActionPreviewResult",
    "ActionTypeVersion",
]
