"""initial schema (baseline)

Revision ID: 9575abae4046
Revises:
Create Date: 2026-06-29 08:27:44.378743+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9575abae4046"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("credential_type", sa.String(length=50), nullable=False),
        sa.Column("secret_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credentials_api_name"), "credentials", ["api_name"], unique=True)
    op.create_table(
        "datasets",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("storage_location", sa.String(length=1024), nullable=False),
        sa.Column("partition_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_dataset_api_name", sa.String(length=255), nullable=True),
        sa.Column("data_source_api_name", sa.String(length=255), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("is_view", sa.Boolean(), nullable=False),
        sa.Column("row_count_estimate", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datasets_api_name"), "datasets", ["api_name"], unique=True)
    op.create_index(op.f("ix_datasets_source_dataset_api_name"), "datasets", ["source_dataset_api_name"], unique=False)
    op.create_table(
        "ontologies",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("rid", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ontologies_api_name"), "ontologies", ["api_name"], unique=True)
    op.create_table(
        "shared_properties",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("data_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_name"),
    )
    op.create_table(
        "structs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("api_name"),
    )
    op.create_table(
        "action_execution_logs",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("action_id", sa.String(length=32), nullable=False),
        sa.Column("action_type_api_name", sa.String(length=255), nullable=False),
        sa.Column("object_type_api_name", sa.String(length=255), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mutations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("performed_by", sa.String(length=255), nullable=False),
        sa.Column("read_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("before_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(op.f("ix_action_execution_logs_action_id"), "action_execution_logs", ["action_id"], unique=False)
    op.create_table(
        "branches",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_branches_ontology_id"), "branches", ["ontology_id"], unique=False)
    op.create_table(
        "data_sources",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("connector_type", sa.String(length=50), nullable=False),
        sa.Column("connector_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("credential_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("gravitino_catalog_name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["credential_id"], ["credentials.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_sources_api_name"), "data_sources", ["api_name"], unique=True)
    op.create_table(
        "interface_types",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("extends_interface_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ontology_id", "api_name", name="uq_interface_types_ontology_api_name"),
    )
    op.create_index(op.f("ix_interface_types_ontology_id"), "interface_types", ["ontology_id"], unique=False)
    op.create_table(
        "link_types",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_object_type_id", sa.String(length=32), nullable=False),
        sa.Column("target_object_type_id", sa.String(length=32), nullable=False),
        sa.Column("foreign_key_property_api_name", sa.String(length=255), nullable=True),
        sa.Column("cardinality", sa.String(length=10), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ontology_id", "api_name", name="uq_link_types_ontology_api_name"),
    )
    op.create_index(op.f("ix_link_types_ontology_id"), "link_types", ["ontology_id"], unique=False)
    op.create_table(
        "object_links",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("link_type_api_name", sa.String(length=255), nullable=False),
        sa.Column("source_object_id", sa.String(length=64), nullable=False),
        sa.Column("target_object_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("link_type_api_name", "source_object_id", "target_object_id", name="uq_object_links"),
    )
    op.create_index(op.f("ix_object_links_link_type_api_name"), "object_links", ["link_type_api_name"], unique=False)
    op.create_index(op.f("ix_object_links_source_object_id"), "object_links", ["source_object_id"], unique=False)
    op.create_index(op.f("ix_object_links_target_object_id"), "object_links", ["target_object_id"], unique=False)
    op.create_table(
        "object_state",
        sa.Column("object_id", sa.String(length=64), nullable=False),
        sa.Column("object_type_api_name", sa.String(length=255), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("modified_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("object_id"),
    )
    op.create_index(
        op.f("ix_object_state_object_type_api_name"), "object_state", ["object_type_api_name"], unique=False
    )
    op.create_table(
        "object_type_groups",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_object_type_groups_ontology_id"), "object_type_groups", ["ontology_id"], unique=False)
    op.create_table(
        "object_types",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("primary_key", sa.String(length=255), nullable=False),
        sa.Column("title_property", sa.String(length=255), nullable=False),
        sa.Column("storage_type", sa.String(length=20), nullable=False),
        sa.Column("visibility", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ontology_id", "api_name", name="uq_object_types_ontology_api_name"),
        comment="本体对象类型定义",
    )
    op.create_index(op.f("ix_object_types_ontology_id"), "object_types", ["ontology_id"], unique=False)
    op.create_table(
        "value_types",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("base_type", sa.String(length=50), nullable=False),
        sa.Column("constraints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ontology_id", "api_name", name="uq_value_types_ontology_api_name"),
    )
    op.create_index(op.f("ix_value_types_ontology_id"), "value_types", ["ontology_id"], unique=False)
    op.create_table(
        "action_types",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("ontology_id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("affected_object_type_id", sa.String(length=32), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("submission_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("risk_level", sa.String(length=10), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("operation_kind", sa.String(length=10), nullable=False),
        sa.Column("batch_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["affected_object_type_id"], ["object_types.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["ontology_id"], ["ontologies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ontology_id", "api_name", name="uq_action_types_ontology_api_name"),
    )
    op.create_index(op.f("ix_action_types_ontology_id"), "action_types", ["ontology_id"], unique=False)
    op.create_table(
        "interface_properties",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("interface_type_id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("data_type", sa.String(length=50), nullable=False),
        sa.Column("is_shared", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["interface_type_id"], ["interface_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_interface_properties_interface_type_id"), "interface_properties", ["interface_type_id"], unique=False
    )
    op.create_table(
        "object_type_shared_properties",
        sa.Column("object_type_id", sa.String(length=32), nullable=False),
        sa.Column("shared_property_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["object_type_id"], ["object_types.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shared_property_id"], ["shared_properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("object_type_id", "shared_property_id"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("action_execution_id", sa.String(length=32), nullable=False),
        sa.Column("effect_type", sa.String(length=50), nullable=False),
        sa.Column("effect_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["action_execution_id"], ["action_execution_logs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbox_action_execution_id"), "outbox", ["action_execution_id"], unique=False)
    op.create_table(
        "properties",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("object_type_id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("data_type", sa.String(length=50), nullable=False),
        sa.Column("is_primary_key", sa.Boolean(), nullable=False),
        sa.Column("is_title_property", sa.Boolean(), nullable=False),
        sa.Column("nullable", sa.Boolean(), nullable=False),
        sa.Column("indexed", sa.Boolean(), nullable=False),
        sa.Column("backing_dataset_api_name", sa.String(length=255), nullable=True),
        sa.Column("backing_catalog", sa.String(length=255), nullable=True),
        sa.Column("backing_schema", sa.String(length=255), nullable=True),
        sa.Column("backing_table", sa.String(length=255), nullable=True),
        sa.Column("backing_column", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["object_type_id"], ["object_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_type_id", "api_name", name="uq_properties_ot_api_name"),
    )
    op.create_index(op.f("ix_properties_object_type_id"), "properties", ["object_type_id"], unique=False)
    op.create_table(
        "sync_tasks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("api_name", sa.String(length=255), nullable=False),
        sa.Column("data_source_id", sa.String(length=32), nullable=False),
        sa.Column("sync_type", sa.String(length=20), nullable=False),
        sa.Column("source_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("target_dataset_api_name", sa.String(length=255), nullable=False),
        sa.Column("sync_mode", sa.String(length=20), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("allow_schema_changes", sa.Boolean(), nullable=False),
        sa.Column("max_duration_minutes", sa.Integer(), nullable=True),
        sa.Column("file_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("pipeline_name", sa.String(length=255), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_tasks_api_name"), "sync_tasks", ["api_name"], unique=True)
    op.create_index(op.f("ix_sync_tasks_data_source_id"), "sync_tasks", ["data_source_id"], unique=False)
    op.create_table(
        "action_type_versions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("action_type_id", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_by", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["action_type_id"], ["action_types.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_type_id", "version", name="uq_action_type_versions"),
    )
    op.create_index(
        op.f("ix_action_type_versions_action_type_id"), "action_type_versions", ["action_type_id"], unique=False
    )

    # ── 部分索引：加速软删除过滤（list 查询默认 WHERE deleted_at IS NULL）──
    # 来源：原 infra/init-pg-schema.sql 的 20260624 migration，ORM 未声明（部分索引
    # 无法在 ORM 层表达），故手动补在初始 revision 里。
    op.create_index(
        "ix_ontologies_active", "ontologies", ["api_name"], unique=False, postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.create_index(
        "ix_object_types_active",
        "object_types",
        ["ontology_id", "api_name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_link_types_active",
        "link_types",
        ["ontology_id", "api_name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_action_types_active",
        "action_types",
        ["ontology_id", "api_name"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_action_types_active", table_name="action_types")
    op.drop_index("ix_link_types_active", table_name="link_types")
    op.drop_index("ix_object_types_active", table_name="object_types")
    op.drop_index("ix_ontologies_active", table_name="ontologies")
    op.drop_index(op.f("ix_action_type_versions_action_type_id"), table_name="action_type_versions")
    op.drop_table("action_type_versions")
    op.drop_index(op.f("ix_sync_tasks_data_source_id"), table_name="sync_tasks")
    op.drop_index(op.f("ix_sync_tasks_api_name"), table_name="sync_tasks")
    op.drop_table("sync_tasks")
    op.drop_index(op.f("ix_properties_object_type_id"), table_name="properties")
    op.drop_table("properties")
    op.drop_index(op.f("ix_outbox_action_execution_id"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_table("object_type_shared_properties")
    op.drop_index(op.f("ix_interface_properties_interface_type_id"), table_name="interface_properties")
    op.drop_table("interface_properties")
    op.drop_index(op.f("ix_action_types_ontology_id"), table_name="action_types")
    op.drop_table("action_types")
    op.drop_index(op.f("ix_value_types_ontology_id"), table_name="value_types")
    op.drop_table("value_types")
    op.drop_index(op.f("ix_object_types_ontology_id"), table_name="object_types")
    op.drop_table("object_types")
    op.drop_index(op.f("ix_object_type_groups_ontology_id"), table_name="object_type_groups")
    op.drop_table("object_type_groups")
    op.drop_index(op.f("ix_object_state_object_type_api_name"), table_name="object_state")
    op.drop_table("object_state")
    op.drop_index(op.f("ix_object_links_target_object_id"), table_name="object_links")
    op.drop_index(op.f("ix_object_links_source_object_id"), table_name="object_links")
    op.drop_index(op.f("ix_object_links_link_type_api_name"), table_name="object_links")
    op.drop_table("object_links")
    op.drop_index(op.f("ix_link_types_ontology_id"), table_name="link_types")
    op.drop_table("link_types")
    op.drop_index(op.f("ix_interface_types_ontology_id"), table_name="interface_types")
    op.drop_table("interface_types")
    op.drop_index(op.f("ix_data_sources_api_name"), table_name="data_sources")
    op.drop_table("data_sources")
    op.drop_index(op.f("ix_branches_ontology_id"), table_name="branches")
    op.drop_table("branches")
    op.drop_index(op.f("ix_action_execution_logs_action_id"), table_name="action_execution_logs")
    op.drop_table("action_execution_logs")
    op.drop_table("structs")
    op.drop_table("shared_properties")
    op.drop_index(op.f("ix_ontologies_api_name"), table_name="ontologies")
    op.drop_table("ontologies")
    op.drop_index(op.f("ix_datasets_source_dataset_api_name"), table_name="datasets")
    op.drop_index(op.f("ix_datasets_api_name"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_index(op.f("ix_credentials_api_name"), table_name="credentials")
    op.drop_table("credentials")
    # ### end Alembic commands ###
