"""add ontology_api_name to object_state for cdc routing

Revision ID: 046a1877a1cf
Revises: 0e2239a90155
Create Date: 2026-07-06 10:22:06.189502+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046a1877a1cf'
down_revision: Union[str, Sequence[str], None] = '0e2239a90155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add ontology_api_name column (denormalized from ontologies via
    # ontology_id) for CDC routing — PG→Kafka transform needs the api_name
    # to build per-type Kafka topic + Doris idx table name idx_{ont}__{type}.
    # server_default='' so existing rows backfill to empty (updated on next
    # Action write); new rows always get the real api_name from ActionService.
    op.add_column('object_state', sa.Column('ontology_api_name', sa.String(length=255), nullable=False, server_default=''))
    op.create_index(op.f('ix_object_state_ontology_api_name'), 'object_state', ['ontology_api_name'], unique=False)
    # Backfill existing rows from ontologies.api_name via ontology_id FK.
    op.execute("UPDATE object_state SET ontology_api_name = o.api_name FROM ontologies o WHERE object_state.ontology_id = o.id")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_object_state_ontology_api_name'), table_name='object_state')
    op.drop_column('object_state', 'ontology_api_name')
    # ### end Alembic commands ###
