"""pipeline_builder_orm_v1

Revision ID: c5a3e0d329ac
Revises: b2c3d4e5f6a7
Create Date: 2026-07-15 12:49:50.379017+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5a3e0d329ac'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # ── Step 1: Create pipeline_versions FIRST (it has FK to pipelines, but
    #    the FK is deferred or handled by creating tables first then adding
    #    the FK after all tables exist). ──
    #
    # Circular FK: pipeline_versions → pipelines (pipeline_id), pipelines →
    # pipeline_versions (current_version_id).  We break the cycle by creating
    # pipeline_versions WITHOUT the FK first, then pipelinss, then add the
    # pipeline_versions FK back.
    op.create_table('pipeline_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pipeline_id', sa.String(length=32), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('graph', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inferred_schema', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    # FK to pipelines added in Step 3 (circular FK workaround)
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'version_number', name='uq_pipeline_versions_number'),
    comment='管道版本历史 — 每次编辑一行，graph JSONB 整存 IR'
    )
    op.create_index(op.f('ix_pipeline_versions_pipeline_id'), 'pipeline_versions', ['pipeline_id'], unique=False)

    # ── Step 2: Create pipelines table (FK to pipeline_versions is valid
    #    because pipeline_versions already exists). ──
    op.create_table('pipelines',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('api_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version_id', sa.String(length=32), nullable=True),
    sa.Column('write_mode', sa.String(length=20), nullable=False),
    sa.Column('sink_dataset_api_name', sa.String(length=255), nullable=False),
    sa.Column('ontology_mapping_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('owner_id', sa.String(length=32), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['pipeline_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='管道定义 — 当前生效版本的元信息'
    )
    op.create_index(op.f('ix_pipelines_api_name'), 'pipelines', ['api_name'], unique=True)
    op.create_index(op.f('ix_pipelines_current_version_id'), 'pipelines', ['current_version_id'], unique=False)
    op.create_index(op.f('ix_pipelines_project_id'), 'pipelines', ['project_id'], unique=False)

    # ── Step 3: Add circular FK back to pipeline_versions ──
    op.create_foreign_key(
        'fk_pipeline_versions_pipeline_id',
        'pipeline_versions', 'pipelines',
        ['pipeline_id'], ['id'],
        ondelete='CASCADE',
    )

    # ── Step 4: Remaining tables (no circular dependencies) ──
    op.create_table('pipeline_executions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pipeline_id', sa.String(length=32), nullable=False),
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=32), nullable=True),
    sa.Column('current_state', sa.String(length=20), nullable=False),
    sa.Column('state_started_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('kestra_execution_id', sa.String(length=255), nullable=True),
    sa.Column('kestra_flow_id', sa.String(length=255), nullable=True),
    sa.Column('kestra_namespace', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('execution_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['version_id'], ['pipeline_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='构建执行记录 — 一次触发一行，冗余当前状态加速列表查询'
    )
    op.create_index(op.f('ix_pipeline_executions_created_at'), 'pipeline_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_current_state'), 'pipeline_executions', ['current_state'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_kestra_execution_id'), 'pipeline_executions', ['kestra_execution_id'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_pipeline_id'), 'pipeline_executions', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_executions_version_id'), 'pipeline_executions', ['version_id'], unique=False)
    op.create_table('pipeline_node_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('engine', sa.String(length=20), nullable=True),
    sa.Column('current_state', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('kestra_taskrun_id', sa.String(length=255), nullable=True),
    sa.Column('rows_in', sa.BigInteger(), nullable=True),
    sa.Column('rows_out', sa.BigInteger(), nullable=True),
    sa.Column('bytes_processed', sa.BigInteger(), nullable=True),
    sa.Column('node_run_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['pipeline_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='节点级执行状态 — 每个构建内节点一行'
    )
    op.create_index(op.f('ix_pipeline_node_runs_current_state'), 'pipeline_node_runs', ['current_state'], unique=False)
    op.create_index(op.f('ix_pipeline_node_runs_execution_id'), 'pipeline_node_runs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_pipeline_node_runs_kestra_taskrun_id'), 'pipeline_node_runs', ['kestra_taskrun_id'], unique=False)
    op.create_table('pipeline_schedules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('pipeline_id', sa.String(length=32), nullable=False),
    sa.Column('api_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('action_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('kestra_trigger_id', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id', 'api_name', name='uq_pipeline_schedules_api_name'),
    comment='管道调度 — 独立资源，一个管道可有多个调度'
    )
    op.create_index(op.f('ix_pipeline_schedules_api_name'), 'pipeline_schedules', ['api_name'], unique=False)
    op.create_index(op.f('ix_pipeline_schedules_pipeline_id'), 'pipeline_schedules', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_schedules_project_id'), 'pipeline_schedules', ['project_id'], unique=False)
    op.create_table('pipeline_state_history',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_by', sa.String(length=32), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['pipeline_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='执行状态变更历史 — 每次状态变更一行'
    )
    op.create_index(op.f('ix_pipeline_state_history_changed_at'), 'pipeline_state_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_pipeline_state_history_execution_id'), 'pipeline_state_history', ['execution_id'], unique=False)
    op.add_column('datasets', sa.Column('current_snapshot_id', sa.String(length=64), nullable=True))
    op.add_column('datasets', sa.Column('snapshot_retention', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('write_lock', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_datasets_current_snapshot_id'), 'datasets', ['current_snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasets_current_snapshot_id'), table_name='datasets')
    op.drop_column('datasets', 'write_lock')
    op.drop_column('datasets', 'snapshot_retention')
    op.drop_column('datasets', 'current_snapshot_id')
    op.drop_index(op.f('ix_pipeline_state_history_execution_id'), table_name='pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_state_history_changed_at'), table_name='pipeline_state_history')
    op.drop_table('pipeline_state_history')
    op.drop_index(op.f('ix_pipeline_schedules_project_id'), table_name='pipeline_schedules')
    op.drop_index(op.f('ix_pipeline_schedules_pipeline_id'), table_name='pipeline_schedules')
    op.drop_index(op.f('ix_pipeline_schedules_api_name'), table_name='pipeline_schedules')
    op.drop_table('pipeline_schedules')
    op.drop_index(op.f('ix_pipeline_node_runs_kestra_taskrun_id'), table_name='pipeline_node_runs')
    op.drop_index(op.f('ix_pipeline_node_runs_execution_id'), table_name='pipeline_node_runs')
    op.drop_index(op.f('ix_pipeline_node_runs_current_state'), table_name='pipeline_node_runs')
    op.drop_table('pipeline_node_runs')
    op.drop_index(op.f('ix_pipeline_executions_version_id'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_pipeline_id'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_kestra_execution_id'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_current_state'), table_name='pipeline_executions')
    op.drop_index(op.f('ix_pipeline_executions_created_at'), table_name='pipeline_executions')
    op.drop_table('pipeline_executions')
    op.drop_index(op.f('ix_pipelines_project_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_current_version_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_api_name'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_pipeline_versions_pipeline_id'), table_name='pipeline_versions')
    op.drop_table('pipeline_versions')
    # ### end Alembic commands ###
