"""add generated_by and generation_meta to row_security_policies

Revision ID: 8549c04f46b9
Revises: 61909bb2e1f6
Create Date: 2026-07-10 14:55:24.461813+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8549c04f46b9'
down_revision: Union[str, Sequence[str], None] = '61909bb2e1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add generated_by + generation_meta to row_security_policies.

    Tracks whether a policy expression was authored by a human ("manual")
    or generated by the LLM policy assistant ("llm", ADR-017 D6). When
    "llm", generation_meta records {prompt, model, ts, reviewer} for audit.
    Both columns are nullable-safe defaults so existing rows are unaffected.
    """
    op.add_column(
        "row_security_policies",
        sa.Column(
            "generated_by",
            sa.String(20),
            nullable=False,
            server_default="manual",
        ),
    )
    op.add_column(
        "row_security_policies",
        sa.Column(
            "generation_meta",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )


def downgrade() -> None:
    """Revert: drop the provenance columns."""
    op.drop_column("row_security_policies", "generation_meta")
    op.drop_column("row_security_policies", "generated_by")
