version: '1.0'
name: deploy-manager
displayName: 部署_Manager_服务
triggers:
  trigger: manual
variables:
  VERSION: "0.5.3"
stages:
  - name: deploy
    displayName: 部署_Manager
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: deploy@k8s
        name: deploy_manager
        displayName: K8S部署_Manager
        version: v1.31.0
        certificate: ${GITCODE_K8S_CERT_ID}
        namespace: unionagents
        yaml: ./deploy/ci/deploy-manager.yaml
        isReplace: false
        skiptls: false
        params:
          VERSION: 0.5.3
          REGISTRY: ${REGISTRY}
        notify: []
        strategy:
          retry: '0'
